name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm build

      - name: Cache built files
        uses: actions/cache@v3
        with:
          path: ./dist
          key: dist-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Restore cached built files
        uses: actions/cache@v3
        with:
          path: ./dist
          key: dist-${{ github.sha }}

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
          cname: smart-space.ntut.club
