name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Quality Scan
        uses: SonarSource/sonarcloud-github-action@v1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
          cname: smart-space.ntut.club
